version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  volumes:
    - .:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-site-command: &site-cmd
  entrypoint: ["node_modules/.bin/basecms-website"]
  command: ["dev", "index.js"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  cli:
    <<: *node
    working_dir: /root/sites
    entrypoint: ["/root/node_modules/.bin/basecms-website"]
    environment:
      <<: *env

  lint:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    command: ["run", "lint"]
    environment:
      <<: *env

  evaluationengineering:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/evaluationengineering
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12151
      LIVERELOAD_PORT: 35151
      GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.base-cms.io/ebm/ee}
    ports:
      - "12151:80"
      - "35151:35151"

  officer:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/officer
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12152
      LIVERELOAD_PORT: 35152
      GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.base-cms.io/ebm/ofcr}
    ports:
      - "12152:80"
      - "35152:35152"

  utilityproducts:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/utilityproducts
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12153
      LIVERELOAD_PORT: 35153
      GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.base-cms.io/ebm/up}
    ports:
      - "12153:80"
      - "35153:35153"

  dentaleconomics:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/dentaleconomics
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12154
      LIVERELOAD_PORT: 35154
      GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.base-cms.io/ebm/de}
    ports:
      - "12154:80"
      - "35154:35154"

  bioopticsworld:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/bioopticsworld
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12155
      LIVERELOAD_PORT: 35155
      GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.base-cms.io/ebm/bow}
    ports:
      - "12155:80"
      - "35155:35155"

  broadbandtechreport:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/broadbandtechreport
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12156
      LIVERELOAD_PORT: 35156
      GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.base-cms.io/ebm/btr}
    ports:
      - "12156:80"
      - "35156:35156"

  cablinginstall:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/cablinginstall
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12157
      LIVERELOAD_PORT: 35157
      GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.base-cms.io/ebm/cim}
    ports:
      - "12157:80"
      - "35157:35157"

  dentistryiq:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/dentistryiq
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12158
      LIVERELOAD_PORT: 35158
      GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.base-cms.io/ebm/diq}
    ports:
      - "12158:80"
      - "35158:35158"
